// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package edu.stanford.slac.aida.dp.dpSlc;

//
// IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI:1.0
//
public class _DpSlcIStub extends org.omg.CORBA.portable.ObjectImpl
                         implements DpSlcI
{
    private static final String[] _ob_ids_ =
    {
        "IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = DpSlcIOperations.class;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/init:1.0
    //
    public void
    init()
        throws edu.stanford.slac.aida.lib.util.except.ServerInitialisationException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("init", true);
                    in = _invoke(out);
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.ServerInitialisationExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.ServerInitialisationExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("init", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    _ob_self.init();
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get:1.0
    //
    public org.omg.CORBA.Any
    get(String _ob_a0,
        String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    org.omg.CORBA.Any _ob_r = in.read_any();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_byte:1.0
    //
    public byte
    get_byte(String _ob_a0,
             String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_byte", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    byte _ob_r = in.read_octet();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_byte", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_byte(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_short:1.0
    //
    public short
    get_short(String _ob_a0,
              String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_short", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    short _ob_r = in.read_short();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_short", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_short(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_long:1.0
    //
    public int
    get_long(String _ob_a0,
             String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_long", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    int _ob_r = in.read_long();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_long", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_long(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_boolean:1.0
    //
    public boolean
    get_boolean(String _ob_a0,
                String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_boolean", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    boolean _ob_r = in.read_boolean();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_boolean", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_boolean(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_double:1.0
    //
    public double
    get_double(String _ob_a0,
               String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_double", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    double _ob_r = in.read_double();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_double", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_double(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_float:1.0
    //
    public float
    get_float(String _ob_a0,
              String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_float", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    float _ob_r = in.read_float();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_float", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_float(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_string:1.0
    //
    public String
    get_string(String _ob_a0,
               String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_string", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    String _ob_r = in.read_string();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_string", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_string(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_char:1.0
    //
    public char
    get_char(String _ob_a0,
             String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_char", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    char _ob_r = in.read_char();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_char", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_char(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_wstring:1.0
    //
    public String
    get_wstring(String _ob_a0,
                String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_wstring", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    String _ob_r = in.read_wstring();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_wstring", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_wstring(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_wchar:1.0
    //
    public char
    get_wchar(String _ob_a0,
              String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_wchar", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    char _ob_r = in.read_wchar();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_wchar", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_wchar(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_bytea:1.0
    //
    public byte[]
    get_bytea(String _ob_a0,
              String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_bytea", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    byte[] _ob_r = org.omg.CORBA.OctetSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_bytea", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_bytea(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_shorta:1.0
    //
    public short[]
    get_shorta(String _ob_a0,
               String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_shorta", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    short[] _ob_r = org.omg.CORBA.ShortSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_shorta", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_shorta(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_longa:1.0
    //
    public int[]
    get_longa(String _ob_a0,
              String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_longa", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    int[] _ob_r = org.omg.CORBA.LongSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_longa", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_longa(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_booleana:1.0
    //
    public boolean[]
    get_booleana(String _ob_a0,
                 String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_booleana", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    boolean[] _ob_r = org.omg.CORBA.BooleanSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_booleana", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_booleana(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_doublea:1.0
    //
    public double[]
    get_doublea(String _ob_a0,
                String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_doublea", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    double[] _ob_r = org.omg.CORBA.DoubleSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_doublea", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_doublea(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_floata:1.0
    //
    public float[]
    get_floata(String _ob_a0,
               String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_floata", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    float[] _ob_r = org.omg.CORBA.FloatSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_floata", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_floata(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_stringa:1.0
    //
    public String[]
    get_stringa(String _ob_a0,
                String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_stringa", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    String[] _ob_r = org.omg.CORBA.StringSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_stringa", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_stringa(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_chara:1.0
    //
    public char[]
    get_chara(String _ob_a0,
              String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_chara", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    char[] _ob_r = org.omg.CORBA.CharSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_chara", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_chara(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_wchara:1.0
    //
    public char[]
    get_wchara(String _ob_a0,
               String[] _ob_a1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_wchara", true);
                    out.write_string(_ob_a0);
                    org.omg.CORBA.StringSeqHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    char[] _ob_r = org.omg.CORBA.WCharSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToGetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_wchara", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_wchara(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/set:1.0
    //
    public void
    set(String _ob_a0,
        org.omg.CORBA.AnyHolder _ob_ah1)
        throws edu.stanford.slac.aida.lib.util.except.UnableToSetDataException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("set", true);
                    out.write_string(_ob_a0);
                    out.write_any(_ob_ah1.value);
                    in = _invoke(out);
                    _ob_ah1.value = in.read_any();
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.UnableToSetDataExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.UnableToSetDataExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("set", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    _ob_self.set(_ob_a0, _ob_ah1);
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/startMonitor:1.0
    //
    public void
    startMonitor(String _ob_a0)
        throws edu.stanford.slac.aida.lib.util.except.MonitorStartupException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("startMonitor", true);
                    out.write_string(_ob_a0);
                    in = _invoke(out);
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.MonitorStartupExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.MonitorStartupExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("startMonitor", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    _ob_self.startMonitor(_ob_a0);
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/stopMonitor:1.0
    //
    public void
    stopMonitor(String _ob_a0)
        throws edu.stanford.slac.aida.lib.util.except.MonitorShutdownException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("stopMonitor", true);
                    out.write_string(_ob_a0);
                    in = _invoke(out);
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.stanford.slac.aida.lib.util.except.MonitorShutdownExceptionHelper.id()))
                        throw edu.stanford.slac.aida.lib.util.except.MonitorShutdownExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("stopMonitor", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    _ob_self.stopMonitor(_ob_a0);
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/status:1.0
    //
    public int
    status()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("status", true);
                    in = _invoke(out);
                    int _ob_r = in.read_long();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("status", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    return _ob_self.status();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/shutdown:1.0
    //
    public void
    shutdown()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("shutdown", true);
                    in = _invoke(out);
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("shutdown", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                DpSlcIOperations _ob_self = (DpSlcIOperations)_ob_so.servant;
                try
                {
                    _ob_self.shutdown();
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
