// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package edu.stanford.slac.aida.dp.dpSlc;

//
// IDL:dp.aida.slac.stanford.edu/dpSlcHist/DpSlcHistI:1.0
//
/***/

public interface DpSlcHistI extends DpSlcHistIOperations,
                                    org.omg.CORBA.Object,
                                    org.omg.CORBA.portable.IDLEntity
{
}
