// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package edu.stanford.slac.aida.dp.dpSlc;

//
// IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI:1.0
//
/***/

public interface DpSlcIOperations
{
    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/init:1.0
    //
    /***/

    void
    init()
        throws edu.stanford.slac.aida.lib.util.except.ServerInitialisationException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get:1.0
    //
    /***/

    org.omg.CORBA.Any
    get(String target,
        String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_byte:1.0
    //
    /***/

    byte
    get_byte(String target,
             String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_short:1.0
    //
    /***/

    short
    get_short(String target,
              String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_long:1.0
    //
    /***/

    int
    get_long(String target,
             String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_boolean:1.0
    //
    /***/

    boolean
    get_boolean(String target,
                String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_double:1.0
    //
    /***/

    double
    get_double(String target,
               String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_float:1.0
    //
    /***/

    float
    get_float(String target,
              String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_string:1.0
    //
    /***/

    String
    get_string(String target,
               String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_char:1.0
    //
    /***/

    char
    get_char(String target,
             String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_wstring:1.0
    //
    /***/

    String
    get_wstring(String target,
                String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_wchar:1.0
    //
    /***/

    char
    get_wchar(String target,
              String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_bytea:1.0
    //
    /***/

    byte[]
    get_bytea(String target,
              String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_shorta:1.0
    //
    /***/

    short[]
    get_shorta(String target,
               String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_longa:1.0
    //
    /***/

    int[]
    get_longa(String target,
              String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_booleana:1.0
    //
    /***/

    boolean[]
    get_booleana(String target,
                 String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_doublea:1.0
    //
    /***/

    double[]
    get_doublea(String target,
                String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_floata:1.0
    //
    /***/

    float[]
    get_floata(String target,
               String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_stringa:1.0
    //
    /***/

    String[]
    get_stringa(String target,
                String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_chara:1.0
    //
    /***/

    char[]
    get_chara(String target,
              String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/get_wchara:1.0
    //
    /***/

    char[]
    get_wchara(String target,
               String[] args)
        throws edu.stanford.slac.aida.lib.util.except.UnableToGetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/set:1.0
    //
    /***/

    void
    set(String target,
        org.omg.CORBA.AnyHolder value)
        throws edu.stanford.slac.aida.lib.util.except.UnableToSetDataException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/startMonitor:1.0
    //
    /***/

    void
    startMonitor(String name)
        throws edu.stanford.slac.aida.lib.util.except.MonitorStartupException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/stopMonitor:1.0
    //
    /***/

    void
    stopMonitor(String name)
        throws edu.stanford.slac.aida.lib.util.except.MonitorShutdownException;

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/status:1.0
    //
    /***/

    int
    status();

    //
    // IDL:dp.aida.slac.stanford.edu/dpSlc/DpSlcI/shutdown:1.0
    //
    /***/

    void
    shutdown();
}
