/*
      **MEMBER**=SLCLIBS:JNISHRLIB
================================================================================
 
  Abs:  Java JNI interface for the Aida dpSlc data provider. This must be
        compiled with specific options to be used with jni so don't compile 
        with cmp.
 
  Name: dpslc_jni.c
        ???func_alloc - a main entry point, for example

  Proto: ??slctxt:mps_proto.hc

  Auth: 05-Nov-2002, Robert C. Sass
  Rev:  ??DD-MMM-YYYY, Reviewer's Name (.NE. Author's Name)
 
--------------------------------------------------------------------------------
 
  Mod:  (newest to oldest)  
        DD-MMM-YYYY, My Name:
           Changed such and such to so and so. etc. etc.
 
==============================================================================*/

   
#include "dpslci_0005fimpl.h" /* Generated by javah */
#include <stdio.h>
#include <string.h>
#include <descrip.h>              /*  for definition of $DESCRIPTOR  */

#include "slctxt:slc_macros.h"    /* vmsstat_t, int2u, int4u, etc. */
#include "slctxt:msg_proto.h"     /* for standalone_init */

extern vmsstat_t MYDB_INIT (void);
extern vmsstat_t MY_DBGET (const char *, float *);
extern vmsstat_t MY_ERR_TRANSLATE (const unsigned long int*,
                                   struct dsc$descriptor*);
/*                                    
** Init for database access.
*/                                  
JNIEXPORT jstring JNICALL Java_DpSlcI_1impl_DbInit(JNIEnv *env, jobject this)
{
   vmsstat_t status;
   char errmsg[256] = { '\0' };
   struct dsc$descriptor errmsg_dsc = 
            {256,DSC$K_DTYPE_T, DSC$K_CLASS_S, (char *)&errmsg};
/*---------------------------------------------------*/
   status = MYDB_INIT ();
   if (!SUCCESS(status))
   {
       MY_ERR_TRANSLATE (&status, &errmsg_dsc);
       errmsg[errmsg_dsc.dsc$w_length] = '\0';  /* Null terminate it */
   }
   return (*env)->NewStringUTF(env, errmsg_dsc.dsc$a_pointer);
}

/*
** DbGet with a string argument.
*/
JNIEXPORT jfloat JNICALL Java_edu_stanford_slac_aida_slc_SlcI_1impl_DbGet (JNIEnv *env, jclass this,
	  jstring dbname) 
{
   float valfloat = 0.0; /* Returned in ieee format */
   vmsstat_t status = 0;
/*---------------------------------------------------*/
   const char *pvname = (*env)->GetStringUTFChars(env, dbname, 0);

   printf ("You have reached DbGet in the shareable, \n");
   printf ("  with name argument = %s \n", pvname);

   if (!SUCCESS(status = MY_DBGET (pvname, &valfloat)))
      printf ("Bad status %x from MY_DBGET\n", status);
   return valfloat;
}
                                                    

/*
** DbPut dummy for now.
*/                                  
JNIEXPORT void JNICALL Java_edu_stanford_slac_aida_slc_SlcI_1impl_DbPut(JNIEnv *env, jobject this)
{
    printf( "You have reached DbPut in the shareable\n" );
    return;
}
                                    
