// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package edu.stanford.slac.aida.dp.dpSlc;

//
// IDL:dp.aida.slac.stanford.edu/dpSlcHist/histData:1.0
//
/***/

final public class histData implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id =
        "IDL:dp.aida.slac.stanford.edu/dpSlc/histData:1.0";

    public
    histData()
    {
    }

    public
    histData(double[] d,
             String[] s,
             int[] repCnt_l)
    {
        this.d = d;
        this.s = s;
        this.repCnt_l = repCnt_l;
    }

    public double[] d;
    public String[] s;
    public int[] repCnt_l;
}
