// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package edu.stanford.slac.aida.dp.dpSlc;

//
// IDL:dp.aida.slac.stanford.edu/dpSlcHist/histData:1.0
//
final public class histDataHelper
{
    public static void
    insert(org.omg.CORBA.Any any, histData val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static histData
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[3];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "d";
            members[0].type = org.omg.CORBA.DoubleSeqHelper.type();

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "s";
            members[1].type = org.omg.CORBA.StringSeqHelper.type();

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "repCnt_l";
            members[2].type = org.omg.CORBA.LongSeqHelper.type();

            typeCode_ = orb.create_struct_tc(id(), "histData", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:dp.aida.slac.stanford.edu/dpChads/histData:1.0";
    }

    public static histData
    read(org.omg.CORBA.portable.InputStream in)
    {
        histData _ob_v = new histData();
        _ob_v.d = org.omg.CORBA.DoubleSeqHelper.read(in);
        _ob_v.s = org.omg.CORBA.StringSeqHelper.read(in);
        _ob_v.repCnt_l = org.omg.CORBA.LongSeqHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, histData val)
    {
        org.omg.CORBA.DoubleSeqHelper.write(out, val.d);
        org.omg.CORBA.StringSeqHelper.write(out, val.s);
        org.omg.CORBA.LongSeqHelper.write(out, val.repCnt_l);
    }
}
