#-*-makefile-*-
#==============================================================
#
#  Abs:  AIDA package release support
#
#  Name: Makefile.Host
#
#  Side: Moves AIDA releasables from $AIDA to standard
#        release framework.
#
#  Rem:  
#
#  Auth: 04-Feb-2005, Greg White (greg)
#
#--------------------------------------------------------------
#  Mod:
#      17-Jun-2008, Greg White (greg)
#        Added oracle examples
#      11-Dec-2007, Bob Hall (rdh)
#        Added klysSetKphrDemo.m.
#      09-Oct-2007, Bob Hall (rdh)
#        Added slcDbSetDemo.m.
#      24-Aug-2007, Bob Hall (rdh)
#        Added klysSetTrimDemo.m.
#      13-Aug-2007, Bob Hall (rdh)
#        Added trigGetDemo.m, trigSetDemo.m, and
#        bgrpDemo.m. 
#      23-May-2007, Bob Hall (rdh)
#        Added klysGetDemo.m and klysSetDemo.m.
#      27-Feb-2007, Bob Hall (rdh)
#        Added masterOscGetDemo.m and masterOscSetDemo.m.
#      13-Dec-2006, Bob Hall (rdh)
#        Added multiknobDemo.m and magnetGetDemo.m.
#      26-Aug-2006, Greg White (greg)
#        Added OrbitDemo and plotOrbitDemo.  
#      07-Apr-2004, Greg White (greg)
#        Added histDemo.m
#
#==============================================================
#
TOP = ../../../../..
INCMK=$(CD_COM_MAKE)
include $(INCMK)/CONFIG_BASE

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
MATS += modelDemo.m
MATS += histDemo.m
MATS += orbitDemo.m
MATS += plotOrbitDemo.m
MATS += multiknobDemo.m
MATS += magnetGetDemo.m
MATS += masterOscGetDemo.m
MATS += masterOscSetDemo.m
MATS += klysGetDemo.m
MATS += klysSetDemo.m
MATS += klysSetTrimDemo.m
MATS += klysSetKphrDemo.m
MATS += trigGetDemo.m
MATS += trigSetDemo.m
MATS += bgrpDemo.m
MATS += slcDbSetDemo.m
MATS += oracleBSAelements.m
MATS += oracleBSAnames.m
MATS += oracleBSAnamesLong.m

include $(INCMK)/RULES.Host
#----------------------------------------
#  ADD RULES AFTER THIS LINE
