#-*-makefile-*-
#==============================================================
#
#  Abs:  AIDA package release "project" Makefile
#
#  Name: Makefile
#
#  Rem:  For Aida matlab stuff
#
#  Auth: greg
#  Rev:  
#
#--------------------------------------------------------------
#  Mod: (lastest to oldest)
#
#        dd-mmm-yyyy, First Last (username):
#           comment
#
#==============================================================
#
TOP = ../..
INCMK=$(CD_COM_MAKE)
include $(INCMK)/CONFIG_BASE
include $(INCMK)/RULES_ARCHS
