#include "OB/Types.idl"

#pragma prefix "dpSlcHist.dp.aida.slac.stanford.edu"

    struct histData
    {
        CORBA::DoubleSeq d;
        CORBA::StringSeq s;
        CORBA::LongSeq repCnt_l;
        CORBA::LongSeq unixtime;
    };
