#!/bin/tcsh

# Check Arguments. Must be at least 1 (the instance name or -h for help)
#
if ($#argv == 1 && ($1 == "-h" || $1 == "-help")) then 
        echo
        echo "Usage: aida_IA  <service-id> <instance> <attribute> [<transform>]"
        echo
	echo "   This example tells Aida to add the instance attribute given, to be processed"
	echo "   by the Oracle Aida data provider, using the SQL statement given:"
	echo
	echo '   E.g. 1: aida_IA 5 '\''BPMS:IN20'\'' '\''BSA.X1H.NAMES'\'' "select unique instance from aida_names where instance like '\'\''BPMS:IN20:%:X1H'\'\''"'
        echo 
        echo "   *NOTE 1* that TWO consecutive single quotes must be used in the argument"
        echo "   to this script, when a single quote is necessary in the SQL statement,"
        echo "   as illustrated in the example above." 
        echo 
	echo "   This example adds an AIDA name whch uses the Name Server facility for"
        echo "   replacing the instance or attribute in the resulting transform text before"
        echo "   handing the result to a data provider for processing. The &instance will"
        echo "   be replaced by the actual instance."
	echo
	echo '   E.g. 2: aida_IA 5 XCOR:IN20:121 suml_m "select suml_m from lcls_infrastructure.v_lcls_elements_report where epics_device_name = '\'\''\&instance'\'\''"'
	echo
	echo "   *NOTE 2*: The & must be escaped by \. See source of this help for an "
        echo "   embeddable example."
#! So a real example, without all the stuff added above so that this help could be 
#! embedded in a c-shell script, as you might have in a script, would be:
#! add_IA 5 XCOR:IN20:121 suml_m "select suml_m from lcls_infrastructure.v_lcls_elements_report where epics_device_name = ''\&instance''"
	echo
        exit 0
endif
if ( $#argv < 3 || $#argv > 4 ) then
        echo "Bad Arguments, see add_IA -h or look in script header"
        exit 1
endif

#source /afs/slac/g/cd/soft/dev/script/oracle_env11g.csh
#setenv ORACLE_PATH .:${ORACLE_PATH}
#setenv ORACLE_PATH ${ORACLE_PATH}:/afs/slac/g/cd/soft/tst/ora
#setenv ORACLE_PATH ${ORACLE_PATH}:/afs/slac/g/cd/soft/dev/ora

#set DB = "$AIDA_DATABASE_USERID/`getPwd $AIDA_DATABASE_USERID`"

if ( $#argv == 4 ) then
sqlplus -S /@${TWO_TASK} <<EOF
set esc on;
@add_IAT "$1" "$2" "$3" "$4"
quit;
EOF
else
sqlplus -S /@${TWO_TASK} <<EOF
set esc on;
@add_IA "$1" "$2" "$3"
quit;
EOF
endif

exit $status

