#!/bin/sh
#-*-sh-*-
#==============================================================
#
#  Abs:   wrapper for "aidacmd get"
#
#  Name:  aidaset
#
#  Rem:   .
#
# 
#  Usage: see aidacmd
#
#  Side:  
#
#  Auth:  16-Nov-2006, Chris Larrieu (clarrieu): 
#  Rev:   
#
#--------------------------------------------------------------
# Mods: (Latest to oldest)
#
#        dd-mmm-yyyy, Whoever (user): 
#            Whatever. 
#
#============================================================== 

exec `dirname $0`/aidacmd set "$@"

