#!/bin/sh
#-*-sh-*-
#==============================================================
#
#  Abs:   start, stop, or restart, Aida suite processes
#
#  Name:  aidamanager
#
#  Rem:   
# 
#  Usage: aidamanager {all,<process-name>} 
#                      {show,start,restart,kill} [{dev,prod]
#         
#    Eg:  aidamanager all show dev           Show all Aida processes on DEV.
#         aidamanager all start              Start all Aida process locally.
#         aidamanager DaServer restart prod  Restart the DaServer on its
#                                              production node.
#
#  Args:  {all,<process-name>}  The published name of an Aida control system
#                               program or process, or "all". If a process
#                               name is given, this should be the 
#                               value of one of the environment variables
#                               named AIDA..._NAME in the list of 
#                               control system processes defined in 
#                               $CD_SOFT/ref/common/setup/setEnv.csh.
#                               
#         [{show,start,restart,kill}]
#                               What to do about the process given in the 
#                               first arg. If this argument is not given, 
#                               warmst just shows the status
#                               of the process given in the first argument.
#                               The default is "show" - just show the pid
#                               of the process given in arg 1, on the host
#                               implied by arg 3 below.
#
#         [{dev,prod,nlcdev,pepii}]
#                               The so-called "hostmode" in which you want to
#                               start, kill etc the process given in the first
#                               argument. This is used to look up the 
#                               actual IP name of the host on which you want
#                               start or kill the process. If this arg is
#                               not given, the host assumed to be localhost.
#                               
#  Side:  
#
#  Auth:  11-Mar-2004, Greg White (greg)
#  Rev:   dd-mmm-yyyy, Whoever    (user):
#
#--------------------------------------------------------------
# Mods: (Latest to oldest)
#        19-Sep-2011, Bob Hall (rdh)
#          Removed AIDA_HST_NAME, AIDA_LHST_NAME, and AIDA_FHST_NAME
#          from all processes.  The Aida AIDAPROD Channel Archiver
#          servers can no longer be started by aidamanger now that
#          the LCLS, FACET, and "Native" (pepii) have been moved from
#          the old Unix Development Environment (e.g., Solaris)
#          mccas0 to the Linux development environment lcls-archsrv.
#        17-Feb-2011, Greg White (greg)
#          Added AIDA_KLYS to all processes list
#        02-Feb-2011, Bob Hall (rdh)
#          Added AIDA_FHST_NAME to all processes.
#        15-Jul-2008, Greg White (greg)
#          Added AIDA_MODEL_NAME to all processes
#        23-Jun-2008, Greg White (greg)
#          Added AIDA_RDB_NAME to all processes
#        05-Apr-2007, Bob Hall (rdh)
#          Added processing for the new LCLS Aida Channel Access
#          data server.
#        10-Mar-2007, Bob Hall (rdh)
#          Added processing for the new LCLS Aida Channel Archiver
#          data server.
#        24-May-2005, Bob Hall (rdh)
#          Added processing logic associated with adding the DpChadsServer
#          history process name to the "allprocesses" list.
#        15-Jan-2005, Greg White (greg)
#          Removed err process servers from "allprocesses", so "aidamanager
#          all" actions don't affect them, use errmanager instead. Also
#          removed AIDA_CA_NAME until that is implemented, and AIDA_HST_NAME
#          until archiver DP is back. 
#        19-May-2004, Greg White (greg)
#          Added $AIDA_TSTH_NAME (DpTestHistServer) to allprocesses
#        07-May-2004, Bob Hall (rdh)
#          Changed to allow hostmode values PACK and ALL.  Also
#          modified to issue commands to all of the DpChadsServer
#          history server processes (DEV, PEPII, NLCDEV, and PACK) if
#          the specified process name is DpChadsServer and the
#          hostmode is ALL.
#        28-Apr-2004, Greg White (greg)
#          Changed name of env vars for Aida processes, so can handle
#          realm names > 4 chars (eg PEPII, NLCDEV). Added PEPII and NLCDEV
#          realms.
#
#============================================================== 

ISS_BAD_ARGS=127
ISS_SUCCESS=0

iss=$ISS_SUCCESS
processName=$1
command=$2
hostmode=`(echo $3|tr '[[:lower:]]' '[[:upper:]]')`
process=""

# All processes in order of activation. If you intended to start them all
# with the "all start" args, you may want to put a pause between each 
# in the for loop below.

allprocesses="$AIDA_NAME_NAME $AIDA_DA_NAME $AIDA_CA_NAME $AIDA_LCA_NAME $AIDA_TST_NAME $AIDA_TSTH_NAME $AIDA_RDB_NAME $AIDA_MODEL_NAME $AIDA_KLYS_NAME"

# Check the hostmode argument is one of those supported in the AIDA process
# family. That is, one of dev,prod.
#
if [ x"$hostmode" != x"DEV" -a \
    x"$hostmode" != x"PROD" -a \
    x"$hostmode" != x"PEPII" -a \
    x"$hostmode" != x"NLCDEV" -a \
    x"$hostmode" != x"PACK" -a \
    x"$hostmode" != x"ALL" -a \
    x"$hostmode" != x"" ] ; then
    echo Bad Argument $hostmode
    exit $ISS_BAD_ARGS
fi

if [ x"$processName" = x"all" ] ; then
    pausetime=0
    if [ x"$command" = x"start" -o \
	x"$command" = x"restart" ] ; then
	pausetime=13
    fi
    for p in $allprocesses
      do
      if [ $iss -eq $ISS_SUCCESS ] ; then
          if [ x"$p" = x"$AIDA_HST_NAME" ] ; then
              if [ x"$hostmode" = x"DEV" ] ; then
                  dev_hist_hostmode="DEV"
                  procmanager $p $command $dev_hist_hostmode
                  iss=$?
                  sleep $pausetime
              elif [ x"$hostmode" = x"PROD" ] ; then
                  prod_hist_hostmodes="PEPII NLCDEV PACK"
                  for m in $prod_hist_hostmodes
                      do
                      if [ $iss -eq $ISS_SUCCESS ] ; then
                          procmanager $p $command $m
                          iss=$?
                          sleep $pausetime
                      fi
                  done
              fi
          else
              procmanager $p $command $hostmode 
              iss=$?
              sleep $pausetime
          fi
      fi
    done
#
#  If the process name is DpChadsServer and the hostmode is ALL,
#  issue the command to all of the DpChadsServer processes.
#
elif [ x"$processName" = x"DpChadsServer" -a x"$hostmode" = x"ALL" ] ; then
    pausetime=0
    if [ x"$command" = x"start" -o \
	x"$command" = x"restart" ] ; then
	pausetime=13
    fi

    all_hist_hostmodes="PEPII NLCDEV PACK DEV"
    for m in $all_hist_hostmodes
      do
      if [ $iss -eq $ISS_SUCCESS ] ; then
	  procmanager $processName $command $m
	  iss=$?
	  sleep $pausetime
      fi
    done

else
    procmanager $processName $command $hostmode
    iss=$?
fi

exit $iss

# End of script
