#!/bin/tcsh -fx
#-*-csh-*-
#==============================================================
###---####!/bin/tcsh -fx
#
#  Abs:   Runs sql scripts to update the given Aida schema 
#         (aidadev or aidaprod) with names derived from those
#         in the SLC Database.
#
#  Name:  aidaPmuNames_update
#
#  Rem:   Runs a sql script to update the aida schema. Note both
#         SLC DB names, and SLC model names are updated by this script, 
#         since both sets are derived from those in secndx.
# 
#  Usage: aidaPmuNames_update {aidadev|aidaprod|aidalcls} <password> 
#         
#  Side:  Changes and commits aidadev or aidaprod
#
#  Auth:  31-Jan-2005, Greg White (greg): 
#  Rev:   dd-mmm-yyyy, Whoever    (user):
#
#--------------------------------------------------------------
# Mods: (Latest to oldest)
#
#        05-Jan-2010, Greg White (greg)
#            Modify to update AIDALCLS also.
#        04-May-2006, Bob Hall (rdh) 
#            Added the invocation of load_aida_slc_db_asts
#            to load the Aida aida_slc_db_asts table. 
#
#============================================================== 

source /afs/slac/g/cd/soft/dev/script/ENVS.csh

date
echo "Setting up environment..."

source /afs/slac/g/cd/soft/dev/script/oracle_env11g.csh
setenv ORACLE_HOME /afs/slac/package/oracle/f/11.1.0/sun4x_59/11.1.0
setenv PATH $ORACLE_HOME/bin:${PATH}
setenv TNS_ADMIN /afs/slac/g/lcls/tools/oracle/wallets/aida

# for oracle scripts
# scripts WERE running from greg, not sure why
# ??? setenv rt /afs/slac/u/cd/greg/cdsoft/aida
setenv ORACLE_PATH /afs/slac/g/cd/soft/ref/package/aida/common/script:/afs/slac/g/cd/soft/dev/ora
echo $ORACLE_PATH

echo '++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'

#date

date
setenv aidaNetwork $1
echo  aidaNetwork is $aidaNetwork
if ( x$aidaNetwork == x"aidadev" ) then
   setenv TWO_TASK SLACPROD
   setenv TNS_ADMIN /afs/slac/g/lcls/tools/oracle/wallets/aidadev
   setenv schema aidadev
   date
   echo "Loading Aida aida_slc_db_asts table for $schema"
   load_aida_slc_db_asts ${schema} 
   date
   echo "Updating $schema from secndx in $TWO_TASK"
   sqlplus /@$TWO_TASK @aidaPmuNames_update.sql
else if ( x$aidaNetwork == x"aidaprod" ) then
   setenv TWO_TASK SLACPROD
   setenv TNS_ADMIN /afs/slac/g/lcls/tools/oracle/wallets/aidaprod
   setenv schema aidaprod
   date
   echo "Loading Aida aida_slc_db_asts table for $schema"
   load_aida_slc_db_asts ${schema} 
   date
   echo "Updating $schema from secndx in $TWO_TASK"
   sqlplus /@$TWO_TASK @aidaPmuNames_update.sql
else if ( x$aidaNetwork == x"aidalcls" ) then
   setenv TWO_TASK MCCQA
   setenv TNS_ADMIN /afs/slac/g/lcls/tools/oracle/wallets/aida
   setenv schema aida
   date
   echo "Loading Aida aida_slc_db_asts table for $schema"
   load_aida_slc_db_asts ${schema} 
   date
   echo "Updating $schema from secndx in $TWO_TASK"
   sqlplus /@$TWO_TASK @aidaPmuNames_update.sql
endif
if ( $status ) then
   echo "ERROR updating aida names for items from secndx, sql exit status = $status"
   exit 1
endif

echo "Updating schema for $1 from secndx ENDS"
date
echo '----------------------------------------------------------------'

exit 0
