#-*-makefile-*-
#==============================================================
#
#  Abs:  AIDA package release "project" Makefile
#
#  Name: Makefile
#
#  Rem:  The project makefile's main job is to decend into sub-directories
#        and issue gmake Makefile.Host in each.
#
#  Auth: greg
#  Rev:  dd-mmm-yyyy, Reviewer's Name (username)
#
#--------------------------------------------------------------
#  Mod: (lastest to oldest)
#
#        dd-mmm-yyyy, First Last (username):
#           comment
#
#==============================================================
#
TOP = ../..
INCMK=$(CD_COM_MAKE)
include $(INCMK)/CONFIG_BASE
include $(INCMK)/RULES_ARCHS
