#!/bin/csh
#! -*- csh -*-
#! Shows Aida directory service contents for a given instance attribute pair. Either
#! instance or attribute (or both) may contain SQLplus wildcards (%).
#! 
#! Check Arguments. Must be at least 1 (the instance name or -h for help)
#!
if ($#argv == 1 && ($1 == "-h" || $1 == "-help")) then 
        echo
	echo "Shows Aida directory service contents for a given instance attribute pair."
	echo "Either instance or attribute (or both) may contain SQLplus wildcards (%)."
	echo
        echo "Usage: show_all  <instance-pattern> <attribute-pattern>"
        echo
	echo "E.g.: show_all XCOR:IN20:% R"
	exit 0
endif

aida_sql_runner show_all ${*}
exit $status
