#
# Abs: Makefile for test package under solaris
#
# Usage: gmake -f Makefile.sun4 
#         - or -
#        gmake -f Makefile.sun4 clean
#
# Sys: solaris makefile, for use with gmake. See Help on GNU web pages
#      for help with gmake.
#
# Auth: 17-Jun-2002, George McIntyre
#
# -----------------------------------------------------------------------------
# Mod:
#       23-May-2011, Greg White
#           Added dpSlcBuff
#       20-Nov-2010, Greg White
#           Added dpKlys
#       21-Jul-2008, Greg White
#           Added Model tests 
#       10-Jun-2008, Greg White
#           Added Rdb tests 
#       06-Feb-2008, Bob Hall
#           Added several Aida Java test files not previously added.
#       07-Oct-2004, Greg White
#           Added Bug test stuff
#       01-Oct-2004, Greg White. 
#           "in all this confusion I clean forgot how many bullets I have". 
#           Removed Simple.java, looks like it never made it to repository.
#       01-Oct-2004, Greg White
#           A little reformatting
#       01-Oct-2004, Bob Hall
#           Added daDpSlcHistTest.java and DpSlcHistTests.java.
#       01-Oct-2004, Greg White
#           Added Simple
#       05-Sep-2004, Greg White
#           Added Err tests.
#       24-Jun-2004, Greg White 
#           Added DaTest, removed daDpTestpTest.java DpTestpTests.java
#       16-Nov-2002, Greg White
#       	Added DpCaTests
#       17-Mar-2003, Ron MacKenzie
#               Added DpChadsTests and daDpChadsTest
#
# =============================================================================
#
PACKAGEROOT	= ../../../../test
PACKAGE		= java
MODULE		= java

LOCALJAVAFILES := TestParser.java \
daAIDATest.java Tests.java \
daApiTest.java ApiTests.java \
daDpCaTest.java DpCaTests.java  \
daDpChadsTest.java DpChadsTests.java  \
daDpSlcTest.java DpSlcTests.java \
daDpSlcHistTest.java DpSlcHistTests.java \
daDpSlcModelTest.java DpSlcModelTests.java \
daDpModelTest.java DpModelTests.java \
daDpSlcBpmTest.java DpSlcBpmTests.java \
daDpSlcBuffTest.java DpSlcBuffTests.java \
daDpSlcKlysTest.java DpSlcKlysTests.java \
daDpKlysTest.java DpKlysTests.java \
daDpSlcMagnetTest.java DpSlcMagnetTests.java \
daDpSlcMoscTest.java DpSlcMoscTests.java \
daDpSlcUtilTest.java DpSlcUtilTests.java \
daDpTestHistTest.java DpTestHistTests.java \
AidaSlcDpServerStatus.java \
AidaUnixDpServerStatus.java \
daErrTest.java ErrTests.java \
daBugTest.java BugTests.java \
daPerfTest.java PerfTests.java \
daDpRdbTest.java DpRdbTests.java \
Simplest.java \
Looping.java \
LoadTest.java \
DaTest.java Matfile.java \
PerformanceUtilities.java

# Append special processing here
$(PACKAGE): all
	@echo programs in $(PACKAGE) are now up-to-date

-include $(AIDADEVROOT)/common/script/MakefileCommon.sun4
include $(AIDA)/common/script/MakefileCommon.sun4

