// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.2.2

package edu.stanford.slac.aida.dp.dpSlcMagnet;

//
// IDL:dp.aida.slac.stanford.edu/dpSlcMagnet/DpSlcMagnetI:1.0
//
/***/

public interface DpSlcMagnetI extends DpSlcMagnetIOperations,
                                      org.omg.CORBA.Object,
                                      org.omg.CORBA.portable.IDLEntity
{
}
