// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.2.2

package edu.stanford.slac.aida.dp.dpSlcMagnet;

//
// IDL:dp.aida.slac.stanford.edu/dpSlcMagnet/DpSlcMagnetI:1.0
//
final public class DpSlcMagnetIHolder implements org.omg.CORBA.portable.Streamable
{
    public DpSlcMagnetI value;

    public
    DpSlcMagnetIHolder()
    {
    }

    public
    DpSlcMagnetIHolder(DpSlcMagnetI initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = DpSlcMagnetIHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        DpSlcMagnetIHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return DpSlcMagnetIHelper.type();
    }
}
