PACKAGEROOT	= tool/
PACKAGE		= command
MODULE		= command
LOCALJAVAFILES := $(wildcard *.java)

# Append special processing here
$(PACKAGE): all
	@echo $(PACKAGE) is up-to-date

-include $(AIDADEVROOT)/common/script/MakefileCommon.sun4
include $(AIDA)/common/script/MakefileCommon.sun4

