#ifndef daNameServer_idl
#define daNameServer_idl

/** CORBA IDL file for AIDA Directory Service ("Name Server").
 * @version 27-Sep-2004 Greg White. Changed exception thrown by getTargetRef from 
 * BadServiceNameException.
 * @version 17-Jun-2002 George McIntyre. Added pragma for package
 */
#include "except.idl"
#include "aidaObjectRef.idl"

#pragma prefix "sys.aida.slac.stanford.edu"

module daNameServer
{
    interface DaNameServerI
    {
        dp::AidaObjectRef getTargetRef( in string target ) raises (except::UndefinedNameException) ;

        void StoreObjRef( in string name, in string ior );   // Store object's reference
        string GetObjRef( in string name );                  // Get object's reference from its name

        long status();      // Get server's status 
        void shutdown();    // Shutdown server 
    };
};

#endif
