#ifndef DPTESTHIST_idl
#define DPTESTHIST_idl
/**
 * IDL for an example AIDA Data Provider which returns IDL defined struct(s).
 *
 * It is anticipated that normally the get() method of an AIDA data provider, 
 * such as DpTest, would return a CORBA Any that has been constructed by the 
 * AIDA utility routine DaValue.toAny() from the aggregate that has been built 
 * by adding objects to a DaValue object. However, AIDA data providers can also
 * choose to return a "raw" Any, for instance, one that has been populated 
 * by streaming data into an Any from a IDL defined struct via the insert() 
 * Helper routine of that struct. An example case is 
 * if the Data Provider is returning data that is already available through
 * CORBA as struct. Another example (as right now) is when the c++ implementation
 * of DaValue is not yet available, so the utility routines for populating it, 
 * and for converting it to an Any (toAny) are not yet available, but we still 
 * need to return a structure.
 *
 * For these reasons this Aida Data Provider has been written to test the raw
 * CORBA any handling of Aida, and illustrates the use of an IDL defined 
 * structure, histData, see bwlow.
 * 
 * @author 16-Oct-2002, Greg White, George McIntyre.
 * @version 06-Aug-2008, Bob Hall.  Added field isdst.
 * @version 05-Oct-2007, Bob Hall.  Added fields unixtime, pulseid, and count.
 * @version 28-Sep-2006, Bob Hall.  Added args parameter to the "set" method.
 * @version 18-Feb-2003, Ron MacKenzie.  Add repeat count to histData.
 */
#include "OB/Types.idl"
#include "except.idl"

#pragma prefix "dp.aida.slac.stanford.edu"

module dpTestHist
{
    struct histData
    {
        CORBA::DoubleSeq d;
        CORBA::StringSeq s;
        CORBA::LongSeq repCnt_l;
        CORBA::LongSeq unixtime;
        CORBA::LongSeq pulseid;
        CORBA::LongSeq count;
        CORBA::LongSeq isdst;
    };

    interface DpTestHistI
    {
        void init() raises (except::ServerInitialisationException) ;

        any get(in string target, in CORBA::StringSeq args) raises (except::UnableToGetDataException) ;

        octet get_byte( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        short get_short( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        long get_long( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        boolean get_boolean( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        double get_double( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        float get_float( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        string get_string( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        char get_char( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        wstring get_wstring( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        wchar get_wchar( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;

        CORBA::OctetSeq get_bytea( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::ShortSeq get_shorta( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::LongSeq get_longa( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::BooleanSeq get_booleana( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::DoubleSeq get_doublea( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::FloatSeq get_floata( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::StringSeq  get_stringa( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::CharSeq get_chara( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;
        CORBA::WCharSeq get_wchara( in string target, in CORBA::StringSeq args ) raises (except::UnableToGetDataException) ;

        void set(in string target, in CORBA::StringSeq args, inout any value) raises (except::UnableToSetDataException) ;

        void startMonitor (in string name) raises (except::MonitorStartupException) ;
        void stopMonitor  (in string name) raises (except::MonitorShutdownException);

        long status();      // Get server's status

        void shutdown();    // Shutdown server
    };
};
#endif
