// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2002
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.2.2

package edu.stanford.slac.aida.dp.dpSlcMosc;

//
// IDL:dp.aida.slac.stanford.edu/dpSlcMosc/DpSlcMoscI:1.0
//
/***/

public interface DpSlcMoscI extends DpSlcMoscIOperations,
                                    org.omg.CORBA.Object,
                                    org.omg.CORBA.portable.IDLEntity
{
}
