AIDA-PVA: edu.stanford.slac.aida.lib.util.AidaPVHelper Class Reference
edu.stanford.slac.aida.lib.util.AidaPVHelper Class Reference
This class provides many functions that help with processing EPICS Process Variables.
Static Public Member Functions
static PVStructure asScalar (Object value)
Convert an arbitrary value to a PVStructure containing an NTScalar
static PVStructure asScalarArray (List<?> values)
Convert an arbitrary list of values to a PVStructure containing an NTScalarArray
static PVStructure asNtTable (List< List< Object > > values, AidaChannelConfig aidaChannelConfig)
Convert an arbitrary list of homogeneously sized columns of values to a PVStructure containing an NTTable The value of each of the columns must be a java List of a type equivalent of one of the supported AIDA-PVA scalar types.
static Type typeOf (AidaType aidaType)
Determine the epics type based on the aida type.
static String ntTypeOf (AidaType aidaType)
Determine the Normative type based on the aida type.
static ScalarType scalarTypeOf (AidaType aidaType)
Determine the epics scalar type based on the aida type.
static String fieldToString (PVField field, String fieldPath, List< FloatArgument > floatArgumentList, List< DoubleArgument > doubleArgumentList) throws RPCRequestException
Extract the String value from the field Any time a double or float is found, add it to the appropriate map under the fieldPath key.
static String structureFieldToString (PVStructure field, String fieldPath, List< FloatArgument > floatArgumentList, List< DoubleArgument > doubleArgumentList) throws RPCRequestException
Convert the PVStructure field to the json string representation of a structure of that field, storing any ieee values found unchanged in the given FloatArgumentand DoubleArgument lists.
static List< String > arrayFieldToStringList (PVArray array, String fieldPath, List< FloatArgument > floatArgumentList, List< DoubleArgument > doubleArgumentList) throws RPCRequestException
Extract array fields as a list of strings.
Static Public Attributes
static final String NT_FIELD_NAME = "value"
The Normative Type specification defines the name of the field containing the value part of its main types (Scalar, ScalarArray, and Table) as "value".
static final String NT_LABELS_NAME = "labels"
The Normative Type specification defines the name of the field containing the labels part of its Table type as "labels".
static final String[] EMPTY_FIELD_NAMES = new String[0]
If you want to add no field names to a structure then use this shortcut.
static final Field[] EMPTY_FIELD_DEFINITIONS = new Field[0]
If you want to add no fields to a structure then use this shortcut.
static final PVStructure NT_SCALAR_EMPTY_STRUCTURE
Shortcut for a complete empty NTTable PVStructure for when no data is returned from the Native Channel Provider from a request.
static final PVStructure NT_SCALAR_ARRAY_EMPTY_STRUCTURE
Shortcut for a complete empty PVStructure containing an NTScalarArray when no data is returned.
static final PVStructure NT_TABLE_EMPTY_STRUCTURE
Shortcut for a complete empty PVStructure containing an NTTable when no data is returned.
Detailed Description
This class provides many functions that help with processing EPICS Process Variables.
APDA-PVA receives data from EPICS in PVField and PVStructure, and we send data back to the EPICS network using the these same data types.
This class provides functions that convert to and from AIDA-PVA java types, and enables creation of the structures and norms required to reply to, and decipher EPICS network requests and data.
Furthermore, we use Normative Types to represent data in a standard way. This is layered on top of Process Variables. So this class also provides constants and standard structures for use with Normative Types. AIDA-PVA Normative Types Documentation
Definition at line 34 of file AidaPVHelper.java.
Member Function Documentation
arrayFieldToStringList()
static List< String > edu.stanford.slac.aida.lib.util.AidaPVHelper.arrayFieldToStringList (PVArray array, String fieldPath, List< FloatArgument > floatArgumentList, List< DoubleArgument > doubleArgumentList) throws RPCRequestException static
Extract array fields as a list of strings.
recurse as necessary.
Parameters
array any PV array
fieldPath the absolute path to the field from the root
floatArgumentList to return the list of floats found and the paths
doubleArgumentList to return the list of doubles found and the paths
Returns
the list of strings for this array
Exceptions
RPCRequestException when there is an unsupported type
Definition at line 675 of file AidaPVHelper.java.
{
        List<String> arrayList = new ArrayList<String>();
        if (array instanceof PVBooleanArray) {
            // For boolean arrays
            booleanArrayToString((PVBooleanArray) array, arrayList);
        } else if (array instanceof PVByteArray) {
            // For byte arrays
            byteArrayToString((PVByteArray) array, arrayList);
        } else if (array instanceof PVShortArray) {
            // For short arrays
            shortArrayToString((PVShortArray) array, arrayList);
        } else if (array instanceof PVIntArray) {
            // For integer arrays
            integerArrayToString((PVIntArray) array, arrayList);
        } else if (array instanceof PVLongArray) {
            // For long arrays
            longArrayToString((PVLongArray) array, arrayList);
        } else if (array instanceof PVFloatArray) {
            // For float arrays
            floatArrayToString((PVFloatArray) array, fieldPath, floatArgumentList, arrayList);
        } else if (array instanceof PVDoubleArray) {
            // For double arrays
            doubleArrayToString((PVDoubleArray) array, fieldPath, doubleArgumentList, arrayList);
        } else if (array instanceof PVStringArray) {
            // For string arrays
            stringArrayToString(array, arrayList);
        } else if (array instanceof PVStructureArray) {
            // For structure arrays then recurse to unpack each field
            structureArrayToString(array, fieldPath, floatArgumentList, doubleArgumentList, arrayList);
        }
        return arrayList;
    }
asNtTable()
static PVStructure edu.stanford.slac.aida.lib.util.AidaPVHelper.asNtTable (List< List< Object > > values, AidaChannelConfig aidaChannelConfig) static
Convert an arbitrary list of homogeneously sized columns of values to a PVStructure containing an NTTable The value of each of the columns must be a java List of a type equivalent of one of the supported AIDA-PVA scalar types.
Boolean, Byte, Short,
Integer, Long, Float,
Double or String
Parameters
values the list of values
aidaChannelConfig the configuration
Returns
the returned PVStructure containing the NT_TABLE
FIRST STAGE PVStructure creation: Structure
SECOND STAGE PVStructure creation: Set values
Definition at line 347 of file AidaPVHelper.java.
{
        // If there is nothing to add or that the list is empty or if the columns are empty return an empty
        //  {@link PVStructure}
        if (values == null || values.isEmpty() || values.get(0).isEmpty()) {
            return NT_TABLE_EMPTY_STRUCTURE;
        }
        // If the lists are not homogeneously sized then raise an exception
        int columnSize = values.get(0).size();
        for (List<Object> column : values) {
            if (column.size() != columnSize) {
                throw new AidaInternalException("Columns in NTTable not homogeneously sized. Normal size: " + columnSize + ", One column size: " + column.size());
            }
        }
        // The field names, labels and types for an NTTable come from the Channel Configuration specified in the
        // CHANNELS.YML file loaded when the service initialises.
        // We need to retrieve these configured values from the given configuration associated with the
        // request we're processing
        List<String> fieldNames = new ArrayList<String>();
        List<String> labels = new ArrayList<String>();
        List<AidaType> aidaTypes = new ArrayList<AidaType>();
        // We need to create a set of fields that we will fill with these values
        List<Field> pvFields = new ArrayList<Field>();
        setFieldsWithNamesLabelsAndTypesFromConfig(pvFields, aidaChannelConfig, values, fieldNames, labels, aidaTypes);
        /// FIRST STAGE {@link PVStructure} creation: Structure
        // List of strings that will contain the labels names
        Field labelsArray = FieldFactory.getFieldCreate().createScalarArray(pvString);
        // Create the second level {@link Field} that will conta
        // top fields, this one holding the structure of the rest of the NTTable
        //  - fieldNames = PVScalarArray containing pvstring and
        //  - columns of values = A set of Fields that are each PVScalarArrays
        Field structure = FieldFactory.getFieldCreate().createStructure(toStringArray(fieldNames), toFieldArray(pvFields));
        // Create the two top fields of the
        Field[] topFields = new Field[] {labelsArray, structure};
        // Create the top {@link PVStructure} that will be returned (labels and values)
        PVStructure retVal = PVFactory.getPVDataCreate().createPVStructure(FieldFactory.getFieldCreate().createStructure(NTTABLE_ID, NT_TABLE_TOP_STRUCTURE_NAMES, topFields));
        /// SECOND STAGE {@link PVStructure} creation: Set values
        // Set the field labels
        setValues(retVal, NT_LABELS_NAME, labels, STRING_ARRAY);
        // Set array values
        for (int i = 0; i < fieldNames.size(); i++) {
            String fieldName = NT_FIELD_NAME + "." + fieldNames.get(i);
            List<?> columnValues = values.get(i);
            AidaType aidaType = aidaTypes.get(i);
            setValues(retVal, fieldName, columnValues, aidaType);
        }
        return retVal;
    }
References edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_FIELD_NAME, edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_LABELS_NAME, and edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_TABLE_EMPTY_STRUCTURE.
asScalar()
static PVStructure edu.stanford.slac.aida.lib.util.AidaPVHelper.asScalar (Object value) static
Convert an arbitrary value to a PVStructure containing an NTScalar
The value must be the java equivalent of one of the supported AIDA-PVA scalar types
Boolean, Byte, Short,
Integer, Long, Float,
Double or String
Parameters
value java equivalent of one of the supported AIDA-PVA scalar types
Returns
PVStructure containing an NTScalar with the value
Definition at line 277 of file AidaPVHelper.java.
{
        // Null values are returned as an empty {@link PVStructure}
        if (value == null) {
            return NT_SCALAR_EMPTY_STRUCTURE;
        }
        // Find out the AIDA-PVA type that corresponds to the given value
        AidaType aidaType = aidaTypeOf(value);
        if (aidaType == null) {
            throw new AidaInternalException("Could not determine type of returned value: " + value);
        }
        // And find out the corresponding PVScalar type that it needs to converted into
        ScalarType scalarType = scalarTypeOf(aidaType);
        // Create the field of that type to be added to the {@link PVStructure} we return
        Field[] scalarField = new Field[] {FieldFactory.getFieldCreate().createScalar(scalarType)};
        // Create a new {@link PVStructure} to return containing the field we created
        PVStructure retVal = PVFactory.getPVDataCreate().createPVStructure(
        // Structure with one element: label and empty scalar field definition
        FieldFactory.getFieldCreate().createStructure(NTSCALAR_ID, NT_SCALAR_TOP_STRUCTURE_NAME, scalarField));
        // In the second phase of {@link PVStructure} creation we now set the field value
        // Note that the field name to set is always called "value" for NT types
        setValue(retVal, value, aidaType);
        return retVal;
    }
References edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_SCALAR_EMPTY_STRUCTURE, and edu.stanford.slac.aida.lib.util.AidaPVHelper.scalarTypeOf().
asScalarArray()
static PVStructure edu.stanford.slac.aida.lib.util.AidaPVHelper.asScalarArray (List<?> values) static
Convert an arbitrary list of values to a PVStructure containing an NTScalarArray
The value must be the java List of a type equivalent of one of the supported AIDA-PVA scalar types
Boolean, Byte, Short,
Integer, Long, Float,
Double or String
Parameters
values the list of values to convert
Returns
PVStructure containing an NTScalarArray with the values
Definition at line 312 of file AidaPVHelper.java.
{
        // Null values are returned as an empty {@link PVStructure}
        if (values == null) {
            return NT_SCALAR_ARRAY_EMPTY_STRUCTURE;
        }
        // Find out the AIDA-PVA type that corresponds to the given values
        AidaType aidaType = aidaTypeOf(values);
        if (aidaType == null) {
            return NT_SCALAR_ARRAY_EMPTY_STRUCTURE;
        }
        // And find out the corresponding PVScalar type that it needs to converted into
        ScalarType scalarType = scalarTypeOf(aidaType);
        // Create the field of that type to be added to the {@link PVStructure} we return
        Field[] scalarArrayField = new Field[] {FieldFactory.getFieldCreate().createScalarArray(scalarType)};
        // Create a new {@link PVStructure} to return containing the field we created
        PVStructure retVal = PVFactory.getPVDataCreate().createPVStructure(
        // Structure with one element: label and empty scalar field definition
        FieldFactory.getFieldCreate().createStructure(NTSCALARARRAY_ID, NT_SCALAR_TOP_STRUCTURE_NAME, scalarArrayField));
        // In the second phase of {@link PVStructure} creation we now set the field value
        // Note that the field name to set is always called "value" for NT types
        setValues(retVal, NT_FIELD_NAME, values, aidaType);
        return retVal;
    }
References edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_FIELD_NAME, edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_SCALAR_ARRAY_EMPTY_STRUCTURE, and edu.stanford.slac.aida.lib.util.AidaPVHelper.scalarTypeOf().
fieldToString()
static String edu.stanford.slac.aida.lib.util.AidaPVHelper.fieldToString (PVField field, String fieldPath, List< FloatArgument > floatArgumentList, List< DoubleArgument > doubleArgumentList) throws RPCRequestException static
Extract the String value from the field Any time a double or float is found, add it to the appropriate map under the fieldPath key.
Parameters
field the field
fieldPath path under which this field sits. Used only for floats and doubles that need to set the path so the name in the pair is prefixed with this value if set
floatArgumentList to return the list of floats found and the paths
doubleArgumentList to return the list of doubles found and the paths
Returns
the extracted value
Exceptions
RPCRequestException of the field type is unsupported
Definition at line 547 of file AidaPVHelper.java.
{
        String value;
        if (field instanceof PVBoolean) {
            value = Boolean.toString(((PVBoolean) field).get());
        } else if (field instanceof PVByte) {
            value = Byte.toString(((PVByte) field).get());
        } else if (field instanceof PVUByte) {
            value = Byte.toString(((PVUByte) field).get());
        } else if (field instanceof PVShort) {
            value = Short.toString(((PVShort) field).get());
        } else if (field instanceof PVInt) {
            value = Integer.toString(((PVInt) field).get());
        } else if (field instanceof PVLong) {
            value = Long.toString(((PVLong) field).get());
        } else if (field instanceof PVFloat) {
            // For float store the ieee value in the list as well
            value = floatFieldToString((PVFloat) field, fieldPath, floatArgumentList);
        } else if (field instanceof PVDouble) {
            // For double store the ieee value in the list as well
            value = doubleFieldToString((PVDouble) field, fieldPath, doubleArgumentList);
        } else if (field instanceof PVString) {
            // For strings quote them is they are subfields but leave them untouched if not
            value = stringFieldToString((PVString) field, fieldPath);
        } else if (field instanceof PVStructure) {
            // For structures recurse for each of the fields
            value = structureFieldToString((PVStructure) field, fieldPath, floatArgumentList, doubleArgumentList);
        } else if (field instanceof PVArray) {
            // For arrays recurse for each of the array elements
            value = arrayFieldToString((PVArray) field, fieldPath, floatArgumentList, doubleArgumentList);
        } else {
            throw new RPCRequestException(ERROR, "Invalid argument value: can only accept scalar, scalar array, structure or structure array");
        }
        return value;
    }
References edu.stanford.slac.aida.lib.util.AidaPVHelper.structureFieldToString().
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.structureFieldToString().
ntTypeOf()
static String edu.stanford.slac.aida.lib.util.AidaPVHelper.ntTypeOf (AidaType aidaType) static
Determine the Normative type based on the aida type.
Parameters
aidaType aida type
Returns
Normative Type String
Definition at line 467 of file AidaPVHelper.java.
{
        switch (aidaType) {
        case BOOLEAN:
        case BYTE:
        case SHORT:
        case INTEGER:
        case LONG:
        case FLOAT:
        case DOUBLE:
        case STRING:
        case SCALAR:
            return NTSCALAR_ID;
        case BOOLEAN_ARRAY:
        case BYTE_ARRAY:
        case SHORT_ARRAY:
        case INTEGER_ARRAY:
        case LONG_ARRAY:
        case FLOAT_ARRAY:
        case DOUBLE_ARRAY:
        case STRING_ARRAY:
        case SCALAR_ARRAY:
            return NTSCALARARRAY_ID;
        case TABLE:
        case ANY:
            return NTTABLE_ID;
        default:
            return null;
        }
    }
scalarTypeOf()
static ScalarType edu.stanford.slac.aida.lib.util.AidaPVHelper.scalarTypeOf (AidaType aidaType) static
Determine the epics scalar type based on the aida type.
Parameters
aidaType aida type
Returns
epics scalar type
Definition at line 503 of file AidaPVHelper.java.
{
        switch (aidaType) {
        case BOOLEAN:
        case BOOLEAN_ARRAY:
            return ScalarType.pvBoolean;
        case BYTE:
        case BYTE_ARRAY:
            return ScalarType.pvByte;
        case INTEGER:
        case INTEGER_ARRAY:
            return ScalarType.pvInt;
        case SHORT:
        case SHORT_ARRAY:
            return ScalarType.pvShort;
        case LONG:
        case LONG_ARRAY:
            return ScalarType.pvLong;
        case DOUBLE:
        case DOUBLE_ARRAY:
            return ScalarType.pvDouble;
        case FLOAT:
        case FLOAT_ARRAY:
            return ScalarType.pvFloat;
        case STRING:
        case STRING_ARRAY:
            return ScalarType.pvString;
        case TABLE:
        default:
            return null;
        }
    }
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.asScalar(), and edu.stanford.slac.aida.lib.util.AidaPVHelper.asScalarArray().
structureFieldToString()
static String edu.stanford.slac.aida.lib.util.AidaPVHelper.structureFieldToString (PVStructure field, String fieldPath, List< FloatArgument > floatArgumentList, List< DoubleArgument > doubleArgumentList) throws RPCRequestException static
Convert the PVStructure field to the json string representation of a structure of that field, storing any ieee values found unchanged in the given FloatArgumentand DoubleArgument lists.
Parameters
field the PVStructure field
fieldPath the absolute path to the field from the root
floatArgumentList the FloatArgument list to store any ieee values
doubleArgumentList the DoubleArgument list to store any ieee values
Returns
the json string representation of the PVStructure
Exceptions
RPCRequestException if anything bad happens
Definition at line 626 of file AidaPVHelper.java.
{
        String value;
        StringBuilder structureBuilder = new StringBuilder();
        structureBuilder.append("{"); // Start of structure
        boolean firstTime = true;
        for (PVField subField : field.getPVFields()) {
            // For each field in structure
            String elementName = subField.getFieldName(); // get the field name
            String absolutePathToElement = fieldPath + "." + elementName; // This is the absolute path to the element from the root of the structure
            // And recurse into the field to get the string representation of it - of course any floats it contains will be stored in the appropriate lists
            String elementValue = fieldToString(subField, absolutePathToElement, floatArgumentList, doubleArgumentList);
            addStructureElementValue(structureBuilder, elementName, elementValue, firstTime);
            firstTime = false;
        }
        structureBuilder.append("}"); // End of structure
        value = structureBuilder.toString();
        return value;
    }
References edu.stanford.slac.aida.lib.util.AidaPVHelper.fieldToString().
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.fieldToString().
typeOf()
static Type edu.stanford.slac.aida.lib.util.AidaPVHelper.typeOf (AidaType aidaType) static
Determine the epics type based on the aida type.
Parameters
aidaType aida type
Returns
epics type
Definition at line 431 of file AidaPVHelper.java.
{
        switch (aidaType) {
        case BOOLEAN:
        case BYTE:
        case SHORT:
        case INTEGER:
        case LONG:
        case FLOAT:
        case DOUBLE:
        case STRING:
        case SCALAR:
            return Type.scalar;
        case BOOLEAN_ARRAY:
        case BYTE_ARRAY:
        case SHORT_ARRAY:
        case INTEGER_ARRAY:
        case LONG_ARRAY:
        case FLOAT_ARRAY:
        case DOUBLE_ARRAY:
        case STRING_ARRAY:
        case SCALAR_ARRAY:
            return Type.scalarArray;
        case TABLE:
        case ANY:
            return Type.structure;
        default:
            return null;
        }
    }
Field Documentation
EMPTY_FIELD_DEFINITIONS
final Field [] edu.stanford.slac.aida.lib.util.AidaPVHelper.EMPTY_FIELD_DEFINITIONS = new Field[0] static
If you want to add no fields to a structure then use this shortcut.
Definition at line 87 of file AidaPVHelper.java.
EMPTY_FIELD_NAMES
final String [] edu.stanford.slac.aida.lib.util.AidaPVHelper.EMPTY_FIELD_NAMES = new String[0] static
If you want to add no field names to a structure then use this shortcut.
Definition at line 83 of file AidaPVHelper.java.
NT_FIELD_NAME
final String edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_FIELD_NAME = "value" static
The Normative Type specification defines the name of the field containing the value part of its main types (Scalar, ScalarArray, and Table) as "value".
Definition at line 66 of file AidaPVHelper.java.
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.asNtTable(), and edu.stanford.slac.aida.lib.util.AidaPVHelper.asScalarArray().
NT_LABELS_NAME
final String edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_LABELS_NAME = "labels" static
The Normative Type specification defines the name of the field containing the labels part of its Table type as "labels".
Definition at line 71 of file AidaPVHelper.java.
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.asNtTable().
NT_SCALAR_ARRAY_EMPTY_STRUCTURE
final PVStructure edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_SCALAR_ARRAY_EMPTY_STRUCTURE static
Initial value:
= PVFactory.getPVDataCreate().createPVStructure(
    FieldFactory.getFieldCreate().createStructure(NTSCALARARRAY_ID, NT_SCALAR_TOP_STRUCTURE_NAME, NT_SCALAR_ARRAY_EMPTY_FIELD))
Shortcut for a complete empty PVStructure containing an NTScalarArray when no data is returned.
Definition at line 112 of file AidaPVHelper.java.
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.asScalarArray().
NT_SCALAR_EMPTY_STRUCTURE
final PVStructure edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_SCALAR_EMPTY_STRUCTURE static
Initial value:
= PVFactory.getPVDataCreate().createPVStructure(
    FieldFactory.getFieldCreate().createStructure(NTSCALAR_ID, NT_SCALAR_TOP_STRUCTURE_NAME, NT_SCALAR_EMPTY_FIELD))
Shortcut for a complete empty NTTable PVStructure for when no data is returned from the Native Channel Provider from a request.
Definition at line 106 of file AidaPVHelper.java.
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.asScalar().
NT_TABLE_EMPTY_STRUCTURE
final PVStructure edu.stanford.slac.aida.lib.util.AidaPVHelper.NT_TABLE_EMPTY_STRUCTURE static
Initial value:
= PVFactory.getPVDataCreate().createPVStructure(
    FieldFactory.getFieldCreate().createStructure(NTTABLE_ID, NT_TABLE_TOP_STRUCTURE_NAMES, NT_TABLE_EMPTY_FIELDS))
Shortcut for a complete empty PVStructure containing an NTTable when no data is returned.
Definition at line 118 of file AidaPVHelper.java.
Referenced by edu.stanford.slac.aida.lib.util.AidaPVHelper.asNtTable().
The documentation for this class was generated from the following file:
root/main/java/edu/stanford/slac/aida/lib/util/AidaPVHelper.java