AIDA-PVA: edu.stanford.slac.aida.lib.ChannelProvider Class Reference
edu.stanford.slac.aida.lib.ChannelProvider Class Reference abstract
Implementation of a Channel Provider.
Public Member Functions
ChannelProvider ()
Constructor for the channel provider that reads the configuration from environment variables and configuration files.
Object requestScalar (String channelName, AidaArguments arguments, AidaType aidaType)
Handles scalar requests by calling the appropriate Native Method.
List<?> requestScalarArray (String channelName, AidaArguments arguments, AidaType aidaType)
Handles scalar array requests by calling the appropriate Native Method.
List< List< Object > > requestTable (String channelName, AidaArguments arguments)
Handles tables by calling the appropriate Native Method.
void setValue (String channelName, AidaArguments arguments)
Handles setting values with a void return by calling the appropriate Native Method.
List< List< Object > > setValueWithResponse (String channelName, AidaArguments arguments)
Handles setting values with a void return by calling the appropriate Native Method.
AidaChannelConfig getSetterConfig (String channelName)
Get Setter configuration.
AidaChannelConfig getGetterConfig (String channelName)
Get Getter configuration.
String getProviderName ()
Get the name of this channel provider.
Set< String > getChannelNames ()
Get the names of the channels hosted by this channel provider.
Additional Inherited Members
Static Public Member Functions inherited from slac.aida.NativeChannelProvider
static native void aidaServiceInit ()
Called once to initialise the channel provider.
Protected Member Functions inherited from slac.aida.NativeChannelProvider
native AidaTable aidaRequestTable (String pvUri, AidaArguments arguments)
Prototype to be implemented for Tables.
native void aidaSetValue (String pvUri, AidaArguments arguments)
Prototype to be implemented for setting values with no return value.
native AidaTable aidaSetValueWithResponse (String pvUri, AidaArguments arguments)
Prototype to be implemented for setting values with a Table as a return value.
native boolean aidaRequestBoolean (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Boolean.
native byte aidaRequestByte (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Byte.
native short aidaRequestShort (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Short.
native int aidaRequestInteger (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Integer.
native long aidaRequestLong (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Long.
native float aidaRequestFloat (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Float.
native double aidaRequestDouble (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Double.
native String aidaRequestString (String pvUri, AidaArguments arguments)
Prototype to be implemented for String.
native boolean[] aidaRequestBooleanArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Boolean Array.
native byte[] aidaRequestByteArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Byte Array.
native short[] aidaRequestShortArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Short Array.
native int[] aidaRequestIntegerArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Integer Array.
native long[] aidaRequestLongArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Long Array.
native float[] aidaRequestFloatArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Float Array.
native double[] aidaRequestDoubleArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Double Array.
native String[] aidaRequestStringArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for String Array.
Detailed Description
Implementation of a Channel Provider.
A Channel Provider is responsible for communicating with the Native Channel Provider to get and receive information from the AIDA-PVA network.
This class encodes generic functionality common to all Channel Providers on the AIDA-PVA network. Specific customisations should be coded in the edu.stanford.slac.aida.impl.AidaChannelProvider class.
This class automatically calls the initialisation of the underlying Native Provider and shows the AIDA-PVA banner.
It also handles the five main classes of requests routing them to the correct underlying
slac.aida.NativeChannelProvider entry point:
ChannelProvider#requestScalar(String, AidaArguments, AidaType)
ChannelProvider#requestScalarArray(String, AidaArguments, AidaType)
ChannelProvider#requestTable(String, AidaArguments)
ChannelProvider#setValue(String, AidaArguments)
ChannelProvider#setValueWithResponse(String, AidaArguments)
Definition at line 49 of file ChannelProvider.java.
Constructor & Destructor Documentation
ChannelProvider()
edu.stanford.slac.aida.lib.ChannelProvider.ChannelProvider ()
Constructor for the channel provider that reads the configuration from environment variables and configuration files.
Uses ChannelProviderFactory#create(ChannelProvider) to check the aida.pva.channels.filename property or the AIDA_PVA_CHANNELS_FILENAME environment variable to load the yaml configuration file
Lists the abbreviated list of hosted channels to the console.
Calls the ChannelProvider#logHostedChannels()
Definition at line 69 of file ChannelProvider.java.
 {
 // Aida server Banner on standard output
          System.out.println(AidaPva.banner());
 // Create the channel based on environment and configuration files
 this.aidaProvider =
          ChannelProviderFactory.create(this);
 // Log the configuration of the channel we just created
 logHostedChannels();
 // Call initialisation for the channel provider
 aidaServiceInit();
 }
References slac.aida.NativeChannelProvider.aidaServiceInit(), edu.stanford.slac.aida.lib.util.AidaPva.banner(), and edu.stanford.slac.aida.lib.ChannelProviderFactory.create().
Member Function Documentation
getChannelNames()
Set< String > edu.stanford.slac.aida.lib.ChannelProvider.getChannelNames ()
Get the names of the channels hosted by this channel provider.
Returns
channel names
Definition at line 243 of file ChannelProvider.java.
 {
 return
          this.aidaProvider.getChannelNames();
 }
References edu.stanford.slac.aida.lib.model.AidaProvider.getChannelNames().
Referenced by edu.stanford.slac.aida.lib.AidaRPCServer.registerServices().
getGetterConfig()
AidaChannelConfig edu.stanford.slac.aida.lib.ChannelProvider.getGetterConfig (String channelName)
Get Getter configuration.
Parameters
channelName the channel name to retrieve configuration
Returns
the configuration
Definition at line 224 of file ChannelProvider.java.
 {
 AidaChannel
          channel = this.aidaProvider.getAidaChannel(channelName);
 return
          (channel == null) ? null : channel.getGetterConfig();
 }
References edu.stanford.slac.aida.lib.model.AidaProvider.getAidaChannel(), and edu.stanford.slac.aida.lib.model.AidaChannel.getGetterConfig().
getProviderName()
String edu.stanford.slac.aida.lib.ChannelProvider.getProviderName ()
Get the name of this channel provider.
Returns
name of channel provider
Definition at line 234 of file ChannelProvider.java.
 {
 return
          this.aidaProvider.getName();
 }
References edu.stanford.slac.aida.lib.model.AidaProvider.getName().
getSetterConfig()
AidaChannelConfig edu.stanford.slac.aida.lib.ChannelProvider.getSetterConfig (String channelName)
Get Setter configuration.
Parameters
channelName the channel name to retrieve configuration
Returns
the configuration
Definition at line 213 of file ChannelProvider.java.
 {
 AidaChannel
          channel = this.aidaProvider.getAidaChannel(channelName);
 return
          (channel == null) ? null : channel.getSetterConfig();
 }
References edu.stanford.slac.aida.lib.model.AidaProvider.getAidaChannel(), and edu.stanford.slac.aida.lib.model.AidaChannel.getSetterConfig().
requestScalar()
Object edu.stanford.slac.aida.lib.ChannelProvider.requestScalar (String channelName, AidaArguments arguments, AidaType aidaType)
Handles scalar requests by calling the appropriate Native Method.
This can return :-
scalars e.g. Boolean, Integer, Byte, Long, Float, Double, ...
Parameters
channelName request channel name
arguments request arguments
aidaType the return type
Returns
object
Definition at line 92 of file ChannelProvider.java.
 {
 switch
          (aidaType) {
 case
          BOOLEAN:
 return
          aidaRequestBoolean(channelName,
          arguments);
 case
          BYTE:
 return
          aidaRequestByte(channelName,
          arguments);
 case
          SHORT:
 return
          aidaRequestShort(channelName,
          arguments);
 case
          INTEGER:
 return
          aidaRequestInteger(channelName,
          arguments);
 case
          LONG:
 return
          aidaRequestLong(channelName,
          arguments);
 case
          FLOAT:
 return
          aidaRequestFloat(channelName,
          arguments);
 case
          DOUBLE:
 return
          aidaRequestDouble(channelName,
          arguments);
 case
          STRING:
 return
          aidaRequestString(channelName,
          arguments);
 }
 return
          null;
 }
References slac.aida.NativeChannelProvider.aidaRequestBoolean(), slac.aida.NativeChannelProvider.aidaRequestByte(), slac.aida.NativeChannelProvider.aidaRequestDouble(), slac.aida.NativeChannelProvider.aidaRequestFloat(), slac.aida.NativeChannelProvider.aidaRequestInteger(), slac.aida.NativeChannelProvider.aidaRequestLong(), slac.aida.NativeChannelProvider.aidaRequestShort(), and slac.aida.NativeChannelProvider.aidaRequestString().
requestScalarArray()
List<?> edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray (String channelName, AidaArguments arguments, AidaType aidaType)
Handles scalar array requests by calling the appropriate Native Method.
This can return :-
collections of scalars e.g. List of Boolean, List of Integer , List of Byte , List of Long , List of Float, List of Double, ...
Parameters
channelName request channel name
arguments request arguments
aidaType the scalar type underpinning this scalar array
Returns
List of scalar object
Definition at line 123 of file ChannelProvider.java.
 {
 switch
          (aidaType) {
 case
          BOOLEAN_ARRAY:
 List<Boolean> tList =
          new ArrayList<Boolean>();
 for
          (Boolean b : aidaRequestBooleanArray(channelName,
          arguments)) {
 tList.add(b);
 }
 return
          tList;
 case
          BYTE_ARRAY:
 List<Byte> bList =
          new ArrayList<Byte>();
 for
          (Byte b : aidaRequestByteArray(channelName,
          arguments)) {
 bList.add(b);
 }
 return
          bList;
 case
          SHORT_ARRAY:
 List<Short> sList =
          new ArrayList<Short>();
 for
          (Short s : aidaRequestShortArray(channelName,
          arguments)) {
 sList.add(s);
 }
 return
          sList;
 case
          INTEGER_ARRAY:
 List<Integer> iList =
          new ArrayList<Integer>();
 for
          (Integer i : aidaRequestIntegerArray(channelName,
          arguments)) {
 iList.add(i);
 }
 return
          iList;
 case
          LONG_ARRAY:
 List<Long> lList =
          new ArrayList<Long>();
 for
          (Long l : aidaRequestLongArray(channelName,
          arguments)) {
 lList.add(l);
 }
 return
          lList;
 case
          FLOAT_ARRAY:
 List<Float> fList =
          new ArrayList<Float>();
 for
          (Float f : aidaRequestFloatArray(channelName,
          arguments)) {
 fList.add(f);
 }
 return
          fList;
 case
          DOUBLE_ARRAY:
 List<Double> dList =
          new ArrayList<Double>();
 for
          (Double d : aidaRequestDoubleArray(channelName,
          arguments)) {
 dList.add(d);
 }
 return
          dList;
 case
          STRING_ARRAY:
 return
          Arrays.asList(aidaRequestStringArray(channelName,
          arguments));
 }
 return
          null;
 }
References slac.aida.NativeChannelProvider.aidaRequestBooleanArray(), slac.aida.NativeChannelProvider.aidaRequestByteArray(), slac.aida.NativeChannelProvider.aidaRequestDoubleArray(), slac.aida.NativeChannelProvider.aidaRequestFloatArray(), slac.aida.NativeChannelProvider.aidaRequestIntegerArray(), slac.aida.NativeChannelProvider.aidaRequestLongArray(), slac.aida.NativeChannelProvider.aidaRequestShortArray(), and slac.aida.NativeChannelProvider.aidaRequestStringArray().
requestTable()
List< List< Object > > edu.stanford.slac.aida.lib.ChannelProvider.requestTable (String channelName, AidaArguments arguments)
Handles tables by calling the appropriate Native Method.
Parameters
channelName channel name
arguments arguments
Returns
return list of lists
Definition at line 180 of file ChannelProvider.java.
 {
 return
          aidaRequestTable(channelName,
          arguments).asList();
 }
References slac.aida.NativeChannelProvider.aidaRequestTable(), and edu.stanford.slac.aida.lib.model.AidaTable.asList().
setValue()
void edu.stanford.slac.aida.lib.ChannelProvider.setValue (String channelName, AidaArguments arguments)
Handles setting values with a void return by calling the appropriate Native Method.
Parameters
channelName channel name
arguments arguments contains
value
that specifies the value as a literal string or in json if it is a table
Definition at line 191 of file ChannelProvider.java.
 {
 aidaSetValue(channelName,
          arguments);
 }
References slac.aida.NativeChannelProvider.aidaSetValue().
setValueWithResponse()
List< List< Object > > edu.stanford.slac.aida.lib.ChannelProvider.setValueWithResponse (String channelName, AidaArguments arguments)
Handles setting values with a void return by calling the appropriate Native Method.
Parameters
channelName channel name
arguments arguments contains
value
that specifies the value as a literal string or in json if it is a table
Returns
return list of lists
Definition at line 203 of file ChannelProvider.java.
 {
 return
          aidaSetValueWithResponse(channelName,
          arguments).asList();
 }
References slac.aida.NativeChannelProvider.aidaSetValueWithResponse(), and edu.stanford.slac.aida.lib.model.AidaTable.asList().
The documentation for this class was generated from the following file:
root/main/java/edu/stanford/slac/aida/lib/ChannelProvider.java