AIDA-PVA: edu.stanford.slac.aida.lib.model.AidaProvider Class Reference
edu.stanford.slac.aida.lib.model.AidaProvider Class Reference
This class encapsulates an AidaProvider.
Public Member Functions
Set< String > getChannelNames ()
Get the set of supported Channel Names.
AidaChannel getAidaChannel (String channelName)
Get the channel based on the channel name.
Long getId ()
The AidaProvider#id identifies the Provider.
String getName ()
The AidaProvider#name identifies the Provider by name.
String getDescription ()
The AidaProvider#description describes what the Provider does.
List< AidaConfigGroup > getConfigurations ()
The AidaProvider#configurations lists the different AidaConfigGroup we define for requests to this channel.
ChannelProvider getChannelProvider ()
The AidaProvider#channelProvider defines the actual class that will implement the functionality to service this channel.
Map< String, AidaChannel > getChannelMap ()
A map of Channel Name => AidaChannel channel configuration, so that configuration can be looked up by Channel Name.
void setId (@NonNull final Long id)
The AidaProvider#id identifies the Provider.
void setName (@NonNull final String name)
The AidaProvider#name identifies the Provider by name.
void setDescription (final String description)
The AidaProvider#description describes what the Provider does.
void setConfigurations (@NonNull final List< AidaConfigGroup > configurations)
The AidaProvider#configurations lists the different AidaConfigGroup we define for requests to this channel.
void setChannelProvider (final ChannelProvider channelProvider)
The AidaProvider#channelProvider defines the actual class that will implement the functionality to service this channel.
.lang.Override boolean equals (final java.lang.Object o)
.lang.Override int hashCode ()
.lang.Override java.lang.String toString ()
Protected Member Functions
boolean canEqual (final java.lang.Object other)
Detailed Description
This class encapsulates an AidaProvider.
It is used configure how an AIDA-PVA will operate.
It has an AidaProvider#id to identify the Provider. It has an AidaProvider#name to give it a name. It has a AidaProvider#description displayed during startup alongside the AidaProvider#id and AidaProvider#name. The AidaProvider#configurations define the different AidaConfigGroup we define for requests to this channel. Finally, the AidaProvider#channelProvider defines the actual class that will implement the functionality to service this channel.
Note that it uses the lombok.Data annotation to provide all the getters and setters. a constructor with all required arguments, and an equals(), hashcode() and toString() method.
It also uses the lombok.NoArgsConstructor annotation to provide a constructor with no arguments.
Definition at line 27 of file AidaProvider.java.
Constructor & Destructor Documentation
AidaProvider()
edu.stanford.slac.aida.lib.model.AidaProvider.AidaProvider ()
Definition at line 341 of file AidaProvider.java.
 {
 }
Member Function Documentation
canEqual()
boolean edu.stanford.slac.aida.lib.model.AidaProvider.canEqual (final java.lang.Object other) protected
Definition at line 310 of file AidaProvider.java.
 {
 return
          other instanceof AidaProvider;
 }
equals()
.lang.Override boolean edu.stanford.slac.aida.lib.model.AidaProvider.equals (final java.lang.Object o)
Definition at line 283 of file AidaProvider.java.
 {
 if
          (o == this) return true;
 if
          (!(o instanceof AidaProvider)) return false;
 final AidaProvider other = (AidaProvider) o;
 if
          (!other.canEqual((java.lang.Object) this)) return false;
 final java.lang.Object this$id = this.getId();
 final java.lang.Object other$id = other.getId();
 if
          (this$id == null ? other$id != null :
          !this$id.equals(other$id)) return false;
 final java.lang.Object this$name = this.getName();
 final java.lang.Object other$name = other.getName();
 if
          (this$name == null ? other$name != null :
          !this$name.equals(other$name)) return false;
 final java.lang.Object this$description = this.getDescription();
 final java.lang.Object other$description = other.getDescription();
 if
          (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
 final java.lang.Object this$configurations = this.getConfigurations();
 final java.lang.Object other$configurations = other.getConfigurations();
 if
          (this$configurations == null ? other$configurations != null : !this$configurations.equals(other$configurations)) return
          false;
 final java.lang.Object this$channelProvider = this.getChannelProvider();
 final java.lang.Object other$channelProvider = other.getChannelProvider();
 if
          (this$channelProvider == null ? other$channelProvider != null
          : !this$channelProvider.equals(other$channelProvider)) return false;
 final java.lang.Object this$channelMap = this.getChannelMap();
 final java.lang.Object other$channelMap = other.getChannelMap();
 if
          (this$channelMap == null ? other$channelMap != null
          : !this$channelMap.equals(other$channelMap)) return false;
 return
          true;
 }
getAidaChannel()
AidaChannel edu.stanford.slac.aida.lib.model.AidaProvider.getAidaChannel (String channelName)
Get the channel based on the channel name.
First, make sure that all config is loaded.
Channels are matched literally but also by using the WildcardMatcher#match to see if any of the patterns specified as supported by this channel correspond to the channel name specified in the request
Parameters
channelName the channel name from the request
Returns
the AidaChannel object that matches the given channel name
Definition at line 84 of file AidaProvider.java.
 {
          loadChannelMapIfNotLoaded();
 // Look for an exact match or a {@link WildcardMatcher#match} if that fails
 AidaChannel aidaChannel =
          this.channelMap.get(channelName);
 if
          (aidaChannel == null) {
 for
          (Map.Entry<String, AidaChannel> entry : this.channelMap.entrySet()) {
 if
          (WildcardMatcher.match(entry.getKey(), channelName)) {
 aidaChannel =
          entry.getValue();
 break;
 }
 }
 }
 return
          aidaChannel;
 }
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.getGetterConfig(), and edu.stanford.slac.aida.lib.ChannelProvider.getSetterConfig().
getChannelMap()
Map< String, AidaChannel > edu.stanford.slac.aida.lib.model.AidaProvider.getChannelMap ()
A map of Channel Name => AidaChannel channel configuration, so that configuration can be looked up by Channel Name.
Definition at line 224 of file AidaProvider.java.
 {
 return
          this.channelMap;
 }
getChannelNames()
Set< String > edu.stanford.slac.aida.lib.model.AidaProvider.getChannelNames ()
Get the set of supported Channel Names.
AIDA-PVA Providers support both AIDA-PVA and legacy AIDA names for their channels. The list returned will contain both.
Returns
the list of supported channel names
Definition at line 67 of file AidaProvider.java.
 {
          loadChannelMapIfNotLoaded();
 return
          this.channelMap.keySet();
 }
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.getChannelNames().
getChannelProvider()
ChannelProvider edu.stanford.slac.aida.lib.model.AidaProvider.getChannelProvider ()
The AidaProvider#channelProvider defines the actual class that will implement the functionality to service this channel.
Definition at line 216 of file AidaProvider.java.
 {
 return
          this.channelProvider;
 }
getConfigurations()
List< AidaConfigGroup > edu.stanford.slac.aida.lib.model.AidaProvider.getConfigurations ()
The AidaProvider#configurations lists the different AidaConfigGroup we define for requests to this channel.
The groups are defined with reference to the appropriate documentation for the Provider. https://www.slac.stanford.edu/grp/cd/soft/aida
Definition at line 208 of file AidaProvider.java.
 {
 return
          this.configurations;
 }
getDescription()
String edu.stanford.slac.aida.lib.model.AidaProvider.getDescription ()
The AidaProvider#description describes what the Provider does.
By convention, we use the AIDA_SERVICES.DESCRIPTION from the AIDA Oracle Database.
Definition at line 198 of file AidaProvider.java.
 {
 return
          this.description;
 }
getId()
Long edu.stanford.slac.aida.lib.model.AidaProvider.getId ()
The AidaProvider#id identifies the Provider.
By convention, we use the AIDA_SERVICES.ID from the AIDA Oracle Database.
Definition at line 179 of file AidaProvider.java.
 {
 return
          this.id;
 }
getName()
String edu.stanford.slac.aida.lib.model.AidaProvider.getName ()
The AidaProvider#name identifies the Provider by name.
By convention, we use the AIDA_SERVICES.NAME from the AIDA Oracle Database.
Definition at line 189 of file AidaProvider.java.
 {
 return
          this.name;
 }
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.getProviderName().
hashCode()
.lang.Override int edu.stanford.slac.aida.lib.model.AidaProvider.hashCode ()
Definition at line 316 of file AidaProvider.java.
 {
 final int PRIME = 59;
 int
          result = 1;
 final java.lang.Object $id = this.getId();
 result = result * PRIME +
          ($id == null ? 43 : $id.hashCode());
 final java.lang.Object $name = this.getName();
 result = result * PRIME +
          ($name == null ? 43 : $name.hashCode());
 final java.lang.Object $description = this.getDescription();
 result = result * PRIME +
          ($description == null ? 43 : $description.hashCode());
 final java.lang.Object $configurations = this.getConfigurations();
 result = result * PRIME +
          ($configurations == null ? 43 : $configurations.hashCode());
 final java.lang.Object $channelProvider = this.getChannelProvider();
 result = result * PRIME +
          ($channelProvider == null ? 43 : $channelProvider.hashCode());
 final java.lang.Object $channelMap = this.getChannelMap();
 result = result * PRIME +
          ($channelMap == null ? 43 : $channelMap.hashCode());
 return
          result;
 }
setChannelProvider()
void edu.stanford.slac.aida.lib.model.AidaProvider.setChannelProvider (final ChannelProvider channelProvider)
The AidaProvider#channelProvider defines the actual class that will implement the functionality to service this channel.
Definition at line 277 of file AidaProvider.java.
 {
 this.channelProvider =
          channelProvider;
 }
Referenced by edu.stanford.slac.aida.lib.ChannelProviderFactory.create().
setConfigurations()
void edu.stanford.slac.aida.lib.model.AidaProvider.setConfigurations (@NonNull final List< AidaConfigGroup > configurations)
The AidaProvider#configurations lists the different AidaConfigGroup we define for requests to this channel.
The groups are defined with reference to the appropriate documentation for the Provider. https://www.slac.stanford.edu/grp/cd/soft/aida
Definition at line 266 of file AidaProvider.java.
 {
 if
          (configurations == null) {
 throw
          new java.lang.NullPointerException("configurations is marked non-null but is null");
 }
 this.configurations =
          configurations;
 }
setDescription()
void edu.stanford.slac.aida.lib.model.AidaProvider.setDescription (final String description)
The AidaProvider#description describes what the Provider does.
By convention, we use the AIDA_SERVICES.DESCRIPTION from the AIDA Oracle Database.
Definition at line 257 of file AidaProvider.java.
 {
 this.description =
          description;
 }
setId()
void edu.stanford.slac.aida.lib.model.AidaProvider.setId (@NonNull final Long id)
The AidaProvider#id identifies the Provider.
By convention, we use the AIDA_SERVICES.ID from the AIDA Oracle Database.
Definition at line 233 of file AidaProvider.java.
 {
 if
          (id == null) {
 throw
          new java.lang.NullPointerException("id is marked non-null but is null");
 }
 this.id = id;
 }
setName()
void edu.stanford.slac.aida.lib.model.AidaProvider.setName (@NonNull final String name)
The AidaProvider#name identifies the Provider by name.
By convention, we use the AIDA_SERVICES.NAME from the AIDA Oracle Database.
Definition at line 245 of file AidaProvider.java.
 {
 if
          (name == null) {
 throw
          new java.lang.NullPointerException("name is marked non-null but is null");
 }
 this.name = name;
 }
toString()
.lang.Override java.lang.String edu.stanford.slac.aida.lib.model.AidaProvider.toString ()
Definition at line 336 of file AidaProvider.java.
 {
 return
          "AidaProvider(id=" + this.getId()
          + ", name=" + this.getName()
          + ", description=" + this.getDescription()
          + ", configurations=" + this.getConfigurations()
          + ", channelProvider=" + this.getChannelProvider()
          + ", channelMap=" + this.getChannelMap()
          + ")";
 }
The documentation for this class was generated from the following file:
root/main/java/edu/stanford/slac/aida/lib/model/AidaProvider.java