AIDA-PVA: slac.aida.NativeChannelProvider Class Reference
slac.aida.NativeChannelProvider Class Reference
This class defines the entry points to all NativeChannel Providers.
Static Public Member Functions
static native void aidaServiceInit ()
Called once to initialise the channel provider.
Protected Member Functions
native AidaTable aidaRequestTable (String pvUri, AidaArguments arguments)
Prototype to be implemented for Tables.
native void aidaSetValue (String pvUri, AidaArguments arguments)
Prototype to be implemented for setting values with no return value.
native AidaTable aidaSetValueWithResponse (String pvUri, AidaArguments arguments)
Prototype to be implemented for setting values with a Table as a return value.
native boolean aidaRequestBoolean (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Boolean.
native byte aidaRequestByte (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Byte.
native short aidaRequestShort (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Short.
native int aidaRequestInteger (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Integer.
native long aidaRequestLong (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Long.
native float aidaRequestFloat (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Float.
native double aidaRequestDouble (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Double.
native String aidaRequestString (String pvUri, AidaArguments arguments)
Prototype to be implemented for String.
native boolean[] aidaRequestBooleanArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Boolean Array.
native byte[] aidaRequestByteArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Byte Array.
native short[] aidaRequestShortArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Short Array.
native int[] aidaRequestIntegerArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Integer Array.
native long[] aidaRequestLongArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Long Array.
native float[] aidaRequestFloatArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Float Array.
native double[] aidaRequestDoubleArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for Scalar Double Array.
native String[] aidaRequestStringArray (String pvUri, AidaArguments arguments)
Prototype to be implemented for String Array.
Detailed Description
This class defines the entry points to all NativeChannel Providers.
All edu.stanford.slac.aida.impl.AidaChannelProviders extend this class so that they can access the native Channel Providers to implement their functionality.
Definition at line 11 of file NativeChannelProvider.java.
Member Function Documentation
aidaRequestBoolean()
native boolean slac.aida.NativeChannelProvider.aidaRequestBoolean (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Boolean.
Parameters
pvUri the uri
arguments the arguments
Returns
a Boolean
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestBooleanArray()
native boolean[] slac.aida.NativeChannelProvider.aidaRequestBooleanArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Boolean Array.
Parameters
pvUri the uri
arguments the arguments
Returns
a Boolean Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestByte()
native byte slac.aida.NativeChannelProvider.aidaRequestByte (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Byte.
Parameters
pvUri the uri
arguments the arguments
Returns
a Byte
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestByteArray()
native byte[] slac.aida.NativeChannelProvider.aidaRequestByteArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Byte Array.
Parameters
pvUri the uri
arguments the arguments
Returns
a Byte Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestDouble()
native double slac.aida.NativeChannelProvider.aidaRequestDouble (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Double.
Parameters
pvUri the uri
arguments the arguments
Returns
a Double
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestDoubleArray()
native double[] slac.aida.NativeChannelProvider.aidaRequestDoubleArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Double Array.
Parameters
pvUri the uri
arguments the arguments
Returns
a Double Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestFloat()
native float slac.aida.NativeChannelProvider.aidaRequestFloat (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Float.
Parameters
pvUri the uri
arguments the arguments
Returns
a Float
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestFloatArray()
native float[] slac.aida.NativeChannelProvider.aidaRequestFloatArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Float Array.
Parameters
pvUri the uri
arguments the arguments
Returns
a Float Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestInteger()
native int slac.aida.NativeChannelProvider.aidaRequestInteger (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Integer.
Parameters
pvUri the uri
arguments the arguments
Returns
ab Integer
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestIntegerArray()
native int[] slac.aida.NativeChannelProvider.aidaRequestIntegerArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Integer Array.
Parameters
pvUri the uri
arguments the arguments
Returns
an Integer Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestLong()
native long slac.aida.NativeChannelProvider.aidaRequestLong (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Long.
Parameters
pvUri the uri
arguments the arguments
Returns
a Long
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestLongArray()
native long[] slac.aida.NativeChannelProvider.aidaRequestLongArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Long Array.
Parameters
pvUri the uri
arguments the arguments
Returns
a Long Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestShort()
native short slac.aida.NativeChannelProvider.aidaRequestShort (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Short.
Parameters
pvUri the uri
arguments the arguments
Returns
a Short
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestShortArray()
native short[] slac.aida.NativeChannelProvider.aidaRequestShortArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Scalar Short Array.
Parameters
pvUri the uri
arguments the arguments
Returns
a Short Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestString()
native String slac.aida.NativeChannelProvider.aidaRequestString (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for String.
Parameters
pvUri the uri
arguments the arguments
Returns
a String
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalar().
aidaRequestStringArray()
native String[] slac.aida.NativeChannelProvider.aidaRequestStringArray (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for String Array.
Parameters
pvUri the uri
arguments the arguments
Returns
a String Array
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestScalarArray().
aidaRequestTable()
native AidaTable slac.aida.NativeChannelProvider.aidaRequestTable (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for Tables.
This is the most commonly implemented method. Tables are simply a list of arbitrary objects. The object is unpacked based on the channel getterConfig.
Parameters
pvUri the uri
arguments the arguments
Returns
a List of AidaTable to be tabulated either ROW_MAJOR (list of rows) or COLUMN_MAJOR (list of columns)
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.requestTable().
aidaSetValue()
native void slac.aida.NativeChannelProvider.aidaSetValue (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for setting values with no return value.
Parameters
pvUri the uri
arguments the arguments
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.setValue().
aidaSetValueWithResponse()
native AidaTable slac.aida.NativeChannelProvider.aidaSetValueWithResponse (String pvUri, AidaArguments arguments) protected
Prototype to be implemented for setting values with a Table as a return value.
Tables are simply a list of arbitrary objects. The object is unpacked based on the channel setterConfig.
Parameters
pvUri the uri
arguments the arguments
Returns
a List of AidaTable to be tabulated either ROW_MAJOR (list of rows) or COLUMN_MAJOR (list of columns)
Referenced by edu.stanford.slac.aida.lib.ChannelProvider.setValueWithResponse().
The documentation for this class was generated from the following file:
root/main/java/slac/aida/NativeChannelProvider.java